### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by katiebutler37** [katiebutler37/readirect#37]
- HTML hardcoded content shouldn't be displayed when page is loaded
- Delete if we can switch fully to dynamically appended content or set display to hide and then remove
- create landing page (greyed out text "Use the search bar to find any book/movie you are looking for) before data is fetched

**Comment by Moshe-jpg** [comment]
- cards shouldn't display onload
- Just search history, footer, and header will display
- results section will be hidden
-
